### ISSUE TITLE
建议将 Google code 上的 Wiki 迁移到 Github 上来？

### ISSUE THREAD

**Issue by hotoo** [rime/rime.github.io#1]
[Rime Wiki](https://code.google.com/p/rimeime/w/list) 内容目前仍然放在 Google code 上，但是：
1. Google code 上的仓库已经不在更新
2. Google code 在中国大陆很多地区目前不可直接访问。

为了更好地维护 Wiki，建议将 Wiki 迁移到 Github 上来。（**最好是通过 Google code wiki 的 svn 迁移到 Github wiki 的 git 仓库，以保留变更记录**）

**Comment by lotem** [comment]
The migration from Google Code in progress.
