### ISSUE TITLE
更新日誌中的Google Code鏈接應該更新。

### ISSUE THREAD

**Issue by kunki** [rime/rime.github.io#3]
由於 rimeime 的 Google Code 站點已經完全無效，所以所有鏈向 Google Code 的地址都應該得到更新。
如：
- [修復：Issue 509](https://github.com/rime/rime.github.io/blob/master/squirrel-update/index.html#L212) 中的鏈接應該更新至[這裏](https://github.com/lotem/rimeime/issues/509)。
- [新增：同步用戶詞典，詳見 Wiki » UserGuide](https://github.com/rime/rime.github.io/blob/master/squirrel-update/index.html#L353) 中的鏈接應該更新至[這裏](https://github.com/rime/home/wiki/UserGuide#%E5%90%8C%E6%AD%A5%E7%94%A8%E6%88%B6%E8%B3%87%E6%96%99)。
- [部落格：拼寫運算調試器](https://github.com/rime/rime.github.io/blob/master/blog/2013/08/28/spelling-algebra-debugger/index.html#L141) 中的鏈接應該更新至[這裏](https://github.com/rime/home/wiki/SpellingAlgebra)。

**Comment by lotem** [comment]
OK
