### ISSUE TITLE
Please support HTTPS

### ISSUE THREAD

**Issue by cotox** [rime/rime.github.io#7]
GitHub Pages supports HTTPS in days.  But the [Rime homepage](http://rime.im) is accessable only in HTTP for now. Can we set it up?

**Comment by lotem** [comment]
GitHub doesn’t support https with custom domain name, which we are using.

**Comment by cotox** [comment]
GitHub supports custom domain on GitHub Pages since May 1, 2018.

See https://blog.github.com/2018-05-01-github-pages-custom-domains-https/.

**Comment by lotem** [comment]
Good news. Why not then.

**Comment by lotem** [comment]
Done.
